### ISSUE TITLE
Task to convert photos from heic to png and to upload them to the aws 

### ISSUE THREAD

**Issue by yashb196** [oss-slu/lrda_mobile#11]
On the add note screen the task is to add the photo either via gallery or taking a photo and then setup a route which allows the photo to be sent to an s3 bucket 

this bucket will then generate a link which should be fetched on the mobile side and sent along with the note

**Comment by Stuartwastaken** [comment]
This issue was resolved by the annotations branch. S3Proxy is still down but for now its behind hosted on a Windows server from @izakrobles home. AWS uploads work for PNG, HEIC, JPEG, and ultimately get sent as a JPEG.
