### ISSUE TITLE
Android Video Upload Problem

### ISSUE THREAD

**Issue by yashb196** [oss-slu/lrda_mobile#113]
Post deployment we have received a feedback to integrate videos to the media uploads

**Comment by irvinet20** [comment]
We encountered the following issue after the following testing:
1. An android video, taken by the camera app on android, and uploaded from an android works.
2. An ios video, taken by camera, and uploaded on ios works.
3. An ios video, pulled from the internet, and uploaded on ios works
4. An android video, pulled from the internet, and uploaded on android, only uploads the thumbnail image and not the video.
The 4th situation is what this issue seeks to resolve.
