### ISSUE TITLE
Deliverable 1: PWA and Photo Upload Functionality

### ISSUE THREAD

**Issue by yashb196** [oss-slu/lrda_mobile#22]
Progressive Web App (PWA) support
        - Implement a fully functional PWA, ensuring compatibility across devices.
        - Conduct thorough testing to identify any bugs or issues within the PWA.
        - Once identified, these bugs should be fixed to ensure smooth operation of the app.
        - The PWA should then be encapsulated within a Docker container for easy deployment and version control.

Photo Uploads
        - Develop a feature to allow users to upload photos via an S3 bucket proxy to AWS servers.
        - When a photo is uploaded, its address should be added to the respective note's JSON object.
        - The uploaded media (photos) should be visible in the 'Edit Note' section.
        - A preview of the uploaded photo should be displayed on the home page next to the corresponding note.
        
        
        Due Date - 06/15/2023

**Comment by izakrobles** [comment]
This was accomplished a while back. Closing issue as changes mentioned have been implemented. PWA support is available and photo uploads are also up and running.
