### ISSUE TITLE
Onboarding feature 

### ISSUE THREAD

**Issue by yashb196** [oss-slu/lrda_mobile#34]
- In the onboarding: Prompt user for location services, teach them how to take notes (etiquette), terms and conditions, privacy policy agreement, purpose of the app, etc.

**Comment by Stuartwastaken** [comment]
Closed in favor of other issues:
https://github.com/oss-slu/lrda_mobile/issues/45
https://github.com/oss-slu/lrda_mobile/issues/46
https://github.com/oss-slu/lrda_mobile/issues/47
