### ISSUE TITLE
Code Refactoring

### ISSUE THREAD

**Issue by izakrobles** [oss-slu/lrda_mobile#37]
The code needs to be refactored. With main components in mind being the API calls and the styling.
- Much of the styling is duplicated and for that reason should be consolidated into separate styling sheets
- There are also duplicate calls for on the APIs
          - API functions should all be defined in a single model, where they can be called in other documents
- Environment variables need to be defined in a .env document in order to hide API keys and addresses from GitHub

**Comment by Stuartwastaken** [comment]
Closed in favor of a more detailed issue:
https://github.com/oss-slu/lrda_mobile/issues/38
