### ISSUE TITLE
Integrate "More" Icon and Related Sections to Navigation Bar

### ISSUE THREAD

**Issue by Stuartwastaken** [oss-slu/lrda_mobile#52]
### Issue:
We need to add a "More" icon to the navigation bar that would replace the current Profile page. Clicking this icon would reveal sections including About, Resources, Profile, Settings, Logout.

### Acceptance Criteria:
- "More" icon is present on the navigation bar and functional.
- Clicking the "More" icon reveals the required sections.

### Note:
This change also includes removing the existing hamburger menu which houses these sections.

**Comment by izakrobles** [comment]
This was merged in with deliverable-5. Resolving
