### ISSUE TITLE
Enable Feature Photo/Media Selection for Notes

### ISSUE THREAD

**Issue by Stuartwastaken** [oss-slu/lrda_mobile#54]
### Issue:
We want users to select their favorite image or video from the set of media attached to a note. The selected media would be the preview featured image on the home page when showing the note for the first time.

### Acceptance Criteria:
- Users can select a favorite photo or video from the media attached to a note.
- Selected media is displayed as the preview featured image on the home page.

### Note:
For video, the thumbnail of the video will be used.

**Comment by izakrobles** [comment]
This was merged in with deliverable-5 resolving
