### ISSUE TITLE
Implement Shimmer Effect on Component Loading

### ISSUE THREAD

**Issue by Stuartwastaken** [oss-slu/lrda_mobile#55]
### Issue:
To improve user experience, we need to implement a shimmer effect for loading components. This should be applied to all components that need to be loaded, such as images, notes, and marker components.

### Acceptance Criteria:
- Shimmer effect is visible when components are loading.
- Shimmer effect is applied to images, notes, and marker components.

**Comment by izakrobles** [comment]
Shimmer in place on loading note and images
