### ISSUE TITLE
Persistant login state

### ISSUE THREAD

**Issue by Stuartwastaken** [oss-slu/lrda_mobile#58]
# Implement Persistent Login State

**Problem:**  
Our app requires users to log in each time it's launched. We need to implement persistent login for better user experience.

**Expected Behavior:**

- Persistent login across multiple app sessions.
- Consistent behavior on both Android and iOS.
- Handle potential issues with stored login state data.

**Additional Context:**  
Refer to this [StackOverflow post](https://stackoverflow.com/questions/39581115/how-to-keep-user-logged-in-aka-state-persistency-in-react-native?rq=1) on maintaining user sessions in React Native.

**Acceptance Criteria:**

- User stays logged in across sessions.
- Functionality consistent on both Android and iOS.
- Effective error handling for login state data issues.
- Relevant tests to ensure functionality.

**Comment by izakrobles** [comment]
This issue was attached to deliverable-5 which was merged to main. Resolving
