### ISSUE TITLE
Dynamic Text

### ISSUE THREAD

**Issue by izakrobles** [oss-slu/lrda_mobile#60]
## Dynamic Text Upgrade

**Problem:** 
In ethnography, expressing details through plain text can be limited. Emotion and emphasis can be added through text styling like bold, italics, underline, and bullet points.

**Expected Behavior:**
- Users should style specific words/characters in notes.
- Available Styles: Bold, Italics, Underline, Bullet Points, etc.

**Additional Context:**
- Use "react-native-pell-rich-editor" for styling.

**Acceptance Criteria:**
- Users can apply styles while writing notes.
- Styles: Bold, Italics, Underline, Bullet Points, etc.
- Use "react-native-pell-rich-editor" in the note screen.
- Provide buttons for styling.
- Applied styles should be saved and displayed in notes.
- Create an intuitive user interface.

**Comment by izakrobles** [comment]
This issue has been resolved. Will close with the merging of Deliverable-6 to main

**Comment by Stuartwastaken** [comment]
Yep added to deliverable-6 getting merged to main soon.
